import React from 'react'
import { useAppStore, Draft } from '../store/app-store'
import { ShadowTooltip } from './ShadowDOMProvider'

interface DraftSelectorProps {
  drafts: Draft[]
}

export const DraftSelector: React.FC<DraftSelectorProps> = ({ drafts }) => {
  const { 
    selectDraft, 
    selectedDraft, 
    setState, 
    canSelectDraft, 
    canStartTyping,
    preventAutoPosting 
  } = useAppStore()

  const handleDraftSelect = (draftId: string) => {
    // Enforce human-in-the-loop: explicit user action required
    const success = selectDraft(draftId, true) // true = explicit user action
    if (!success) {
      console.warn('Draft selection failed - human-in-the-loop validation')
    }
  }

  const handleUseSelected = () => {
    // Validate state machine allows typing
    if (!canStartTyping()) {
      console.warn('Cannot start typing - invalid state')
      return
    }
    
    // Ensure we have a selected draft
    if (!selectedDraft) {
      console.warn('Cannot start typing - no draft selected')
      return
    }
    
    // Enforce human-in-the-loop: never auto-post
    if (!preventAutoPosting()) {
      console.error('SECURITY: Auto-posting attempted - blocked by human-in-the-loop governance')
      return
    }
    
    setState('typing', 'User explicitly selected draft for typing')
  }

  // Disable selection if state machine doesn't allow it
  const canSelect = canSelectDraft()

  return (
    <div className="space-y-3">
      <div className="text-sm font-medium text-gray-700">
        Select a draft to use:
      </div>
      
      {!canSelect && (
        <div className="text-xs text-amber-600 bg-amber-50 p-2 rounded">
          Draft selection not available in current state
        </div>
      )}
      
      <div className="space-y-2 max-h-60 overflow-y-auto">
        {drafts.map((draft) => (
          <ShadowTooltip
            key={draft.id}
            content={
              canSelect 
                ? `Generated by ${draft.provider} • Click to select`
                : 'Draft selection disabled'
            }
            side="left"
          >
            <div
              className={`p-3 border rounded transition-colors ${
                !canSelect
                  ? 'border-gray-100 bg-gray-50 cursor-not-allowed opacity-50'
                  : draft.selected 
                    ? 'border-blue-500 bg-blue-50 cursor-pointer' 
                    : 'border-gray-200 hover:border-gray-300 cursor-pointer'
              }`}
              onClick={canSelect ? () => handleDraftSelect(draft.id) : undefined}
            >
              <div className="text-sm text-gray-900 line-clamp-3">
                {draft.content}
              </div>
              <div className="text-xs text-gray-500 mt-1">
                via {draft.provider}
              </div>
            </div>
          </ShadowTooltip>
        ))}
      </div>
      
      {selectedDraft && canStartTyping() && (
        <ShadowTooltip content="Insert the selected draft into the post (human approval required)">
          <button
            onClick={handleUseSelected}
            className="w-full bg-blue-600 text-white py-2 px-4 rounded text-sm font-medium hover:bg-blue-700 transition-colors"
          >
            Use Selected Draft
          </button>
        </ShadowTooltip>
      )}
      
      {selectedDraft && !canStartTyping() && (
        <div className="text-xs text-amber-600 bg-amber-50 p-2 rounded">
          Cannot proceed to typing - state machine validation failed
        </div>
      )}
    </div>
  )
}